name: docker_psycher

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */7 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build and publish
        run: |
          chmod +x ./psycher.sh
          ./psycher.sh
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
