name: docker_psycher

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */7 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build and publish
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{secrets.DOCKER_USERNAME}}", "password": "${{secrets.DOCKER_PASSWORD}}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
          REPO_LIST=$(curl -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${{secrets.DOCKER_USERNAME}}/?page_size=100 | jq -r '.results|.[]|.name')
          echo $REPO_LIST

          for i in ${REPO_LIST}
          do

            IMAGE_TAGS=$(curl -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${{secrets.DOCKER_USERNAME}}/${i}/tags/?page_size=1 | jq -r '.results|.[]|.name')

            for j in ${IMAGE_TAGS}
            do
              FULL_IMAGE_LIST="${FULL_IMAGE_LIST} ${{secrets.DOCKER_USERNAME}}/${i}:${j}"
            done
          done

          for i in ${FULL_IMAGE_LIST}
          do
            docker pull ${i}
          done

          # docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
