name: docker_psycher

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */7 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build and publish
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{secrets.DOCKER_USERNAME}}", "password": "${{secrets.DOCKER_PASSWORD}}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)

          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
